#!/bin/bash
if [ -e script.sh ] && [ -s script.sh ] ; then

   echo "fichier existe et non vide"
else
   echo "fichier vide"
fi

# if [ -e fichier ] pour voir si un fichier existe
# if [ ! -s fichier ] pour voir si un fichier est non vide

